del *.xml
del *.pif
del *.aps
del *.ncb
del *.ini
del *.user
del *.sdf
del *.bak
del TMP*.$$$
del *.exe
del /a:a *.suo
del Release\*.obj
del Release\*.htm
del Release\*.pdb
del Release\*.idb
del Release\*.res
del Release\*.manifest
del Release\*.dep
del Release\*.lastbuildstate
del Release\*.log
del Release\*.tlog
del Release\*.m3u8
del Release\*.ini
del Release\*.iobj
del Release\*.ipdb
del Debug\*.obj
del Debug\*.htm
del Debug\*.pdb
del Debug\*.idb
del Debug\*.res
del Debug\*.manifest
del Debug\*.dep
del Debug\*.lastbuildstate
del Debug\*.log
del Debug\*.tlog
del Debug\*.ilk
del Debug\*.rc
del Debug\*.exe
del Debug\*.m3u8
del Debug\*.ini
del Debug\*.csv
del Debug\*.vsp
rmdir /q /s ipch
rmdir /q /s Release\Hayaemon.tlog
