//----------------------------------------------------------------------------
// CommandList.cpp : コマンドIDリストを管理する
//----------------------------------------------------------------------------
#include "CommandList.h"

//--------------------------------------------------------------------------
// COMMAND LIST
//--------------------------------------------------------------------------
ST_CMDLIST cmdlist[] = {
#if JP
{DIV_FILE,       CMD_ALL,    ID_OPENFILE,              _T("ファイルを開く")},
{DIV_FILE,       CMD_KEYMENU,ID_ADDFILE,               _T("ファイルを追加")},
{DIV_FILE,       CMD_KEYMENU,ID_OPENFOLDER,            _T("フォルダを開く")},
{DIV_FILE,       CMD_KEYMENU,ID_ADDFOLDER,             _T("フォルダを追加")},
{DIV_FILE,       CMD_KEYMENU,ID_OPENURL,               _T("URLを開く")},
{DIV_FILE,       CMD_KEYMENU,ID_ADDURL,                _T("URLを追加")},
{DIV_FILE,       CMD_KEYMENU,ID_SAVEFILE,              _T("ファイルを保存")},
{DIV_FILE,       CMD_KEYMENU,ID_SAVEALLFILE,           _T("一括変換")},
{DIV_FILE,       CMD_KEYMENU,ID_LAMECOMMANDLINE,       _T("LAMEコマンドラインオプションの設定")},
{DIV_FILE,       CMD_KEYMENU,ID_EXIT,                  _T("終了")},
{DIV_EDIT,       CMD_KEYMENU,ID_DELETE,                _T("削除")},
{DIV_EDIT,       CMD_KEYMENU,ID_SELECTALL,             _T("全て選択")},
{DIV_VIEW,       CMD_KEYMENU,ID_VIDEOSCREEN,           _T("ビデオ画面")},
{DIV_VIEW,       CMD_KEYMENU,ID_LYRICS,                _T("歌詞の表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_PITCHANALYSER,         _T("ピッチアナライザの表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_TIMESLIDER,            _T("再生位置スライダ")},
{DIV_VIEW,       CMD_KEYMENU,ID_EXPLORER,              _T("エクスプローラ")},
{DIV_VIEW,       CMD_KEYMENU,ID_SPEED,                 _T("再生速度コントロールを表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_FREQ,                  _T("再生周波数コントロールを表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_PITCH,                 _T("音程コントロールを表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_VOLUME,                _T("音量コントロールを表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_PAN,                   _T("パンコントロールを表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ,                    _T("グラフィックイコライザを表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ20,                  _T("グラフィックイコライザ（20Hz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ25,                  _T("グラフィックイコライザ（25Hz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ31_5,                _T("グラフィックイコライザ（31.5Hz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ40,                  _T("グラフィックイコライザ（40Hz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ50,                  _T("グラフィックイコライザ（50Hz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ63,                  _T("グラフィックイコライザ（63Hz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ80,                  _T("グラフィックイコライザ（80Hz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ100,                 _T("グラフィックイコライザ（100Hz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ125,                 _T("グラフィックイコライザ（125Hz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ160,                 _T("グラフィックイコライザ（160Hz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ200,                 _T("グラフィックイコライザ（200Hz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ250,                 _T("グラフィックイコライザ（250Hz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ315,                 _T("グラフィックイコライザ（315Hz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ400,                 _T("グラフィックイコライザ（400Hz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ500,                 _T("グラフィックイコライザ（500Hz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ630,                 _T("グラフィックイコライザ（630Hz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ800,                 _T("グラフィックイコライザ（800Hz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ1K,                  _T("グラフィックイコライザ（1KHz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ1_25K,               _T("グラフィックイコライザ（1.25KHz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ1_6K,                _T("グラフィックイコライザ（1.6KHz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ2K,                  _T("グラフィックイコライザ（2KHz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ2_5K,                _T("グラフィックイコライザ（2.5KHz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ3_15K,               _T("グラフィックイコライザ（3.15KHz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ4K,                  _T("グラフィックイコライザ（4KHz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ5K,                  _T("グラフィックイコライザ（5KHz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ6_3K,                _T("グラフィックイコライザ（6.3KHz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ8K,                  _T("グラフィックイコライザ（8KHz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ10K,                 _T("グラフィックイコライザ（10KHz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ12_5K,               _T("グラフィックイコライザ（12.5KHz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ16K,                 _T("グラフィックイコライザ（16KHz）を表示")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ20K,                 _T("グラフィックイコライザ（20KHz）を表示")},
{DIV_VIEW,       CMD_ALL,    ID_PLAYLIST,              _T("再生リストを表示")},
{DIV_VIEW,       CMD_ALL,    ID_TAB,                   _T("タブを表示")},
{DIV_VIEW,       CMD_ALL,    ID_CLOSEALL,              _T("全てのコントロールを閉じる")},
{DIV_VIEW,       CMD_KEYMENU,ID_TOOLBAR_SIZES,         _T("ツールバーのサイズ（小）")},
{DIV_VIEW,       CMD_KEYMENU,ID_TOOLBAR_SIZEM,         _T("ツールバーのサイズ（中）")},
{DIV_VIEW,       CMD_KEYMENU,ID_TOOLBAR_SIZEL,         _T("ツールバーのサイズ（大）")},
{DIV_VIEW,       CMD_KEYMENU,ID_CUSTOMIZETOOLBAR,      _T("ツールバーのカスタマイズ")},
{DIV_PLAY,       CMD_TOOLBAR,ID_PLAY,                  _T("再生")},
{DIV_PLAY,       CMD_ALL,    ID_PAUSE,                 _T("再生/一時停止")},
{DIV_PLAY,       CMD_ALL,    ID_STOP,                  _T("停止")},
{DIV_PLAY,       CMD_ALL,    ID_HEAD,                  _T("頭出し")},
{DIV_PLAY,       CMD_NONE,   ID_PREVMARKER,            _T("前のマーカーへ")},
{DIV_PLAY,       CMD_KEYMENU,ID_PREV,                  _T("前へ")},
{DIV_PLAY,       CMD_NONE,   ID_NEXTMARKER,            _T("次のマーカーへ")},
{DIV_PLAY,       CMD_ALL,    ID_NEXT,                  _T("次へ")},
{DIV_PLAY,       CMD_KEYMENU,ID_REWIND,                _T("巻き戻し")},
{DIV_PLAY,       CMD_KEYMENU,ID_FORWARD,               _T("早送り")},
{DIV_BACKWARD,   CMD_KEYSET, ID_PAUSE_RETURN1SEC,      _T("一時停止後1秒戻る")},
{DIV_BACKWARD,   CMD_KEYSET, ID_PAUSE_RETURN2SEC,      _T("一時停止後2秒戻る")},
{DIV_BACKWARD,   CMD_KEYSET, ID_PAUSE_RETURN3SEC,      _T("一時停止後3秒戻る")},
{DIV_BACKWARD,   CMD_KEYSET, ID_PAUSE_RETURN5SEC,      _T("一時停止後5秒戻る")},
{DIV_BACKWARD,   CMD_KEYSET, ID_PAUSE_RETURN10SEC,     _T("一時停止後10秒戻る")},
{DIV_BACKWARD,   CMD_KEYMENU,ID_RETURN1SEC,            _T("1秒戻る")},
{DIV_BACKWARD,   CMD_KEYMENU,ID_RETURN2SEC,            _T("2秒戻る")},
{DIV_BACKWARD,   CMD_KEYMENU,ID_RETURN3SEC,            _T("3秒戻る")},
{DIV_BACKWARD,   CMD_KEYMENU,ID_RETURN5SEC,            _T("5秒戻る")},
{DIV_BACKWARD,   CMD_KEYMENU,ID_RETURN10SEC,           _T("10秒戻る")},
{DIV_FORWARD,    CMD_KEYMENU,ID_FORWARD1SEC,           _T("1秒進む")},
{DIV_FORWARD,    CMD_KEYMENU,ID_FORWARD2SEC,           _T("2秒進む")},
{DIV_FORWARD,    CMD_KEYMENU,ID_FORWARD3SEC,           _T("3秒進む")},
{DIV_FORWARD,    CMD_KEYMENU,ID_FORWARD5SEC,           _T("5秒進む")},
{DIV_FORWARD,    CMD_KEYMENU,ID_FORWARD10SEC,          _T("10秒進む")},
{DIV_SPEED,      CMD_KEYMENU,ID_RESETSPEED,            _T("再生速度をデフォルトに戻す")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_50,              _T("再生速度を50%にする")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_60,              _T("再生速度を60%にする")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_70,              _T("再生速度を70%にする")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_80,              _T("再生速度を80%にする")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_90,              _T("再生速度を90%にする")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_100,             _T("再生速度を100%にする")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_110,             _T("再生速度を110%にする")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_120,             _T("再生速度を120%にする")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_130,             _T("再生速度を130%にする")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_140,             _T("再生速度を140%にする")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_150,             _T("再生速度を150%にする")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_160,             _T("再生速度を160%にする")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_170,             _T("再生速度を170%にする")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_180,             _T("再生速度を180%にする")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_190,             _T("再生速度を190%にする")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_200,             _T("再生速度を200%にする")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_250,             _T("再生速度を250%にする")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_300,             _T("再生速度を300%にする")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_350,             _T("再生速度を350%にする")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_400,             _T("再生速度を400%にする")},
{DIV_SPEED,      CMD_KEYMENU,ID_DOWN0_1SPEED,          _T("再生速度を0.1%下げる")},
{DIV_SPEED,      CMD_KEYMENU,ID_DOWN1SPEED,            _T("再生速度を1%下げる")},
{DIV_SPEED,      CMD_KEYMENU,ID_DOWN2SPEED,            _T("再生速度を2%下げる")},
{DIV_SPEED,      CMD_KEYMENU,ID_DOWN3SPEED,            _T("再生速度を3%下げる")},
{DIV_SPEED,      CMD_KEYMENU,ID_DOWN5SPEED,            _T("再生速度を5%下げる")},
{DIV_SPEED,      CMD_KEYMENU,ID_DOWN10SPEED,           _T("再生速度を10%下げる")},
{DIV_SPEED,      CMD_KEYMENU,ID_UP0_1SPEED,            _T("再生速度を0.1%上げる")},
{DIV_SPEED,      CMD_KEYMENU,ID_UP1SPEED,              _T("再生速度を1%上げる")},
{DIV_SPEED,      CMD_KEYMENU,ID_UP2SPEED,              _T("再生速度を2%上げる")},
{DIV_SPEED,      CMD_KEYMENU,ID_UP3SPEED,              _T("再生速度を3%上げる")},
{DIV_SPEED,      CMD_KEYMENU,ID_UP5SPEED,              _T("再生速度を5%上げる")},
{DIV_SPEED,      CMD_KEYMENU,ID_UP10SPEED,             _T("再生速度を10%上げる")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEEDDEC_0,            _T("再生速度の小数点桁数を0桁にする")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEEDDEC_1,            _T("再生速度の小数点桁数を1桁にする")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEEDDEC_2,            _T("再生速度の小数点桁数を2桁にする")},
{DIV_FREQ,       CMD_KEYMENU,ID_RESETFREQ,             _T("再生周波数をデフォルトに戻す")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_50,              _T("再生周波数を50%にする")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_60,              _T("再生周波数を60%にする")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_70,              _T("再生周波数を70%にする")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_80,              _T("再生周波数を80%にする")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_90,              _T("再生周波数を90%にする")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_100,             _T("再生周波数を100%にする")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_110,             _T("再生周波数を110%にする")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_120,             _T("再生周波数を120%にする")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_130,             _T("再生周波数を130%にする")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_140,             _T("再生周波数を140%にする")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_150,             _T("再生周波数を150%にする")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_160,             _T("再生周波数を160%にする")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_170,             _T("再生周波数を170%にする")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_180,             _T("再生周波数を180%にする")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_190,             _T("再生周波数を190%にする")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_200,             _T("再生周波数を200%にする")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_250,             _T("再生周波数を250%にする")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_300,             _T("再生周波数を300%にする")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_350,             _T("再生周波数を350%にする")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_400,             _T("再生周波数を400%にする")},
{DIV_FREQ,       CMD_KEYMENU,ID_DOWN0_1FREQ,           _T("再生周波数を0.1%下げる")},
{DIV_FREQ,       CMD_KEYMENU,ID_DOWN1FREQ,             _T("再生周波数を1%下げる")},
{DIV_FREQ,       CMD_KEYMENU,ID_DOWN2FREQ,             _T("再生周波数を2%下げる")},
{DIV_FREQ,       CMD_KEYMENU,ID_DOWN3FREQ,             _T("再生周波数を3%下げる")},
{DIV_FREQ,       CMD_KEYMENU,ID_DOWN5FREQ,             _T("再生周波数を5%下げる")},
{DIV_FREQ,       CMD_KEYMENU,ID_DOWN10FREQ,            _T("再生周波数を10%下げる")},
{DIV_FREQ,       CMD_KEYMENU,ID_UP0_1FREQ,             _T("再生周波数を0.1%上げる")},
{DIV_FREQ,       CMD_KEYMENU,ID_UP1FREQ,               _T("再生周波数を1%上げる")},
{DIV_FREQ,       CMD_KEYMENU,ID_UP2FREQ,               _T("再生周波数を2%上げる")},
{DIV_FREQ,       CMD_KEYMENU,ID_UP3FREQ,               _T("再生周波数を3%上げる")},
{DIV_FREQ,       CMD_KEYMENU,ID_UP5FREQ,               _T("再生周波数を5%上げる")},
{DIV_FREQ,       CMD_KEYMENU,ID_UP10FREQ,              _T("再生周波数を10%上げる")},
{DIV_FREQ,       CMD_KEYMENU,ID_FREQDEC_0,             _T("再生周波数の小数点桁数を0桁にする")},
{DIV_FREQ,       CMD_KEYMENU,ID_FREQDEC_1,             _T("再生周波数の小数点桁数を1桁にする")},
{DIV_FREQ,       CMD_KEYMENU,ID_FREQDEC_2,             _T("再生周波数の小数点桁数を2桁にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_RESETPITCH,            _T("音程をデフォルトに戻す")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_F12,             _T("音程を♭12にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_F11,             _T("音程を♭11にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_F10,             _T("音程を♭10にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_F9,              _T("音程を♭9にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_F8,              _T("音程を♭8にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_F7,              _T("音程を♭7にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_F6,              _T("音程を♭6にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_F5,              _T("音程を♭5にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_F4,              _T("音程を♭4にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_F3,              _T("音程を♭3にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_F2,              _T("音程を♭2にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_F1,              _T("音程を♭1にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_0,               _T("音程を原音にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_S1,              _T("音程を♯1にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_S2,              _T("音程を♯2にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_S3,              _T("音程を♯3にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_S4,              _T("音程を♯4にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_S5,              _T("音程を♯5にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_S6,              _T("音程を♯6にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_S7,              _T("音程を♯7にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_S8,              _T("音程を♯8にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_S9,              _T("音程を♯9にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_S10,             _T("音程を♯10にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_S11,             _T("音程を♯11にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_S12,             _T("音程を♯12にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_DOWN1PITCH,            _T("音程を半音下げる")},
{DIV_PITCH,      CMD_KEYMENU,ID_DOWN2PITCH,            _T("音程を全音下げる")},
{DIV_PITCH,      CMD_KEYMENU,ID_DOWN1OCTPITCH,         _T("音程を１オクターブ下げる")},
{DIV_PITCH,      CMD_KEYMENU,ID_UP1PITCH,              _T("音程を半音上げる")},
{DIV_PITCH,      CMD_KEYMENU,ID_UP2PITCH,              _T("音程を全音上げる")},
{DIV_PITCH,      CMD_KEYMENU,ID_UP1OCTPITCH,           _T("音程を１オクターブ上げる")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCHDEC_0,            _T("音程の小数点桁数を0桁にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCHDEC_1,            _T("音程の小数点桁数を1桁にする")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCHDEC_2,            _T("音程の小数点桁数を2桁にする")},
{DIV_PLAY,       CMD_KEYMENU,ID_RESETVOLUME,           _T("音量をデフォルトに戻す")},
{DIV_PLAY,       CMD_KEYMENU,ID_VOLUME_0,              _T("音量を0%にする")},
{DIV_PLAY,       CMD_KEYMENU,ID_VOLUME_10,             _T("音量を10%にする")},
{DIV_PLAY,       CMD_KEYMENU,ID_VOLUME_20,             _T("音量を20%にする")},
{DIV_PLAY,       CMD_KEYMENU,ID_VOLUME_30,             _T("音量を30%にする")},
{DIV_PLAY,       CMD_KEYMENU,ID_VOLUME_40,             _T("音量を40%にする")},
{DIV_PLAY,       CMD_KEYMENU,ID_VOLUME_50,             _T("音量を50%にする")},
{DIV_PLAY,       CMD_KEYMENU,ID_VOLUME_60,             _T("音量を60%にする")},
{DIV_PLAY,       CMD_KEYMENU,ID_VOLUME_70,             _T("音量を70%にする")},
{DIV_PLAY,       CMD_KEYMENU,ID_VOLUME_80,             _T("音量を80%にする")},
{DIV_PLAY,       CMD_KEYMENU,ID_VOLUME_90,             _T("音量を90%にする")},
{DIV_PLAY,       CMD_KEYMENU,ID_VOLUME_100,            _T("音量を100%にする")},
{DIV_PLAY,       CMD_KEYSET, ID_UPVOLUME,              _T("音量を1%上げる")},
{DIV_PLAY,       CMD_KEYSET, ID_DOWNVOLUME,            _T("音量を1%下げる")},
{DIV_PLAY,       CMD_ALL,    ID_SLOOP,                 _T("１曲ループ")},
{DIV_PLAY,       CMD_ALL,    ID_ALOOP,                 _T("全曲ループ")},
{DIV_PLAY,       CMD_ALL,    ID_RANDOM,                _T("ランダム再生")},
{DIV_PLAY,       CMD_KEYMENU,ID_CONTINUE,              _T("連続再生")},
{DIV_PLAY,       CMD_ALL,    ID_SAMEARTIST,            _T("同じアーティストの曲を再生")},
{DIV_PLAY,       CMD_ALL,    ID_ABLOOP_A,              _T("ＡＢループ（Ａ）")},
{DIV_PLAY,       CMD_ALL,    ID_ABLOOP_A_SETTING,      _T("ＡＢループ（Ａ）の位置指定")},
{DIV_PLAY,       CMD_ALL,    ID_ABLOOP_B,              _T("ＡＢループ（Ｂ）")},
{DIV_PLAY,       CMD_ALL,    ID_ABLOOP_B_SETTING,      _T("ＡＢループ（Ｂ）の位置設定")},
{DIV_PLAY,       CMD_ALL,    ID_MARKERPLAY,            _T("マーカー再生")},
{DIV_PLAY,       CMD_ALL,    ID_ADDMARKER,             _T("マーカー追加")},
{DIV_PLAY,       CMD_ALL,    ID_DELETEMARKER,          _T("マーカー削除")},
{DIV_PLAY,       CMD_KEYMENU,ID_COUNTLOOP,             _T("回数ループ")},
{DIV_PLAY,       CMD_KEYMENU,ID_INSTANTLOOP,           _T("マーカー追加時にループ")},
{DIV_PLAY,       CMD_KEYMENU,ID_SETPOSITIONAUTO,       _T("マーカー調整時の再生位置連動")},
{DIV_RCV_VISIBLE,CMD_KEYMENU,ID_RECOVERVIDEOSCREENVISIBLE,_T("ビデオ画面の復元")},
{DIV_RCV_VISIBLE,CMD_KEYMENU,ID_RECOVERTIMESLIDERVISIBLE,_T("再生位置スライダの復元")},
{DIV_RCV_VISIBLE,CMD_KEYMENU,ID_RECOVERSPEEDVISIBLE,   _T("再生速度表示状態の復元")},
{DIV_RCV_VISIBLE,CMD_KEYMENU,ID_RECOVERFREQVISIBLE,    _T("再生周波数表示状態の復元")},
{DIV_RCV_VISIBLE,CMD_KEYMENU,ID_RECOVERPITCHVISIBLE,   _T("音程表示状態の復元")},
{DIV_RCV_VISIBLE,CMD_KEYMENU,ID_RECOVERVOLUMEVISIBLE,  _T("音量表示状態の復元")},
{DIV_RCV_VISIBLE,CMD_KEYMENU,ID_RECOVERPANVISIBLE,     _T("パン表示状態の復元")},
{DIV_RCV_VISIBLE,CMD_KEYMENU,ID_RECOVEREQVISIBLE,      _T("グラフィックイコライザ表示状態の復元")},
{DIV_RCV_VISIBLE,CMD_KEYMENU,ID_RECOVERLISTVISIBLE,    _T("再生リスト表示状態の復元")},
{DIV_RCV_MODE,   CMD_KEYMENU,ID_RECOVERSLOOP,          _T("１曲ループの復元")},
{DIV_RCV_MODE,   CMD_KEYMENU,ID_RECOVERALOOP,          _T("全曲ループの復元")},
{DIV_RCV_MODE,   CMD_KEYMENU,ID_RECOVERRANDOM,         _T("ランダム再生の復元")},
{DIV_RCV_MODE,   CMD_KEYMENU,ID_RECOVERCONTINUE,       _T("連続再生の復元")},
{DIV_RCV_MODE,   CMD_KEYMENU,ID_RECOVERINSTANTLOOP,    _T("マーカー追加時にループ")},
{DIV_RCV_MODE,   CMD_KEYMENU,ID_RECOVERSETPOSITIONAUTO,_T("マーカー位置変更時に再生位置変更")},
{DIV_RCV_MODE,   CMD_KEYMENU,ID_RECOVERREVERSE,        _T("逆回転再生の復元")},
{DIV_RCV_MODE,   CMD_KEYMENU,ID_RECOVERRECORD,         _T("古びたレコード再生の復元")},
{DIV_RECOVERY,   CMD_KEYMENU,ID_RECOVERWPOS,           _T("ウィンドウ位置の復元")},
{DIV_RECOVERY,   CMD_KEYMENU,ID_RECOVERWSIZE,          _T("ウィンドウサイズの復元")},
{DIV_RECOVERY,   CMD_KEYMENU,ID_RECOVERPLAYPOS,        _T("再生位置の復元")},
{DIV_RECOVERY,   CMD_KEYMENU,ID_RECOVERSPEED,          _T("再生速度の復元")},
{DIV_RECOVERY,   CMD_KEYMENU,ID_RECOVERFREQ,           _T("再生周波数の復元")},
{DIV_RECOVERY,   CMD_KEYMENU,ID_RECOVERPITCH,          _T("音程の復元")},
{DIV_RECOVERY,   CMD_KEYMENU,ID_RECOVERVOLUME,         _T("音量の復元")},
{DIV_RECOVERY,   CMD_KEYMENU,ID_RECOVERPAN,            _T("パンの復元")},
{DIV_RECOVERY,   CMD_KEYMENU,ID_RECOVEREQ,             _T("グラフィックイコライザの復元")},
{DIV_RECOVERY,   CMD_KEYMENU,ID_RECOVERLIST,           _T("再生リストの復元")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_KEYSETTING,            _T("ショートカットキー設定")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_OUTKEYSETTING,         _T("グローバルホットキー設定")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_TIMERPLAY,             _T("タイマー設定")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_LIMIT,                 _T("最大値／最小値の設定")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_PLAYRANGE,             _T("再生範囲")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_PLAYPOSITION,          _T("再生位置")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_INCSPEED,              _T("再生速度をだんだん速くする")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_INCFREQ,               _T("再生周波数をだんだん速くする")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_DECSPEED,              _T("再生速度をだんだん遅くする")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_DECFREQ,               _T("再生周波数をだんだん遅くする")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_FADEOUTSTOP,           _T("再生停止時にフェードアウト")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_FADEOUTSTOP1SEC,       _T("停止時フェードアウト時間を1秒に設定")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_FADEOUTSTOP2SEC,       _T("停止時フェードアウト時間を2秒に設定")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_FADEOUTSTOP3SEC,       _T("停止時フェードアウト時間を3秒に設定")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_FADEOUTSTOP4SEC,       _T("停止時フェードアウト時間を4秒に設定")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_FADEOUTSTOP5SEC,       _T("停止時フェードアウト時間を5秒に設定")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_FADEOUTSTOP6SEC,       _T("停止時フェードアウト時間を6秒に設定")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_FADEOUTSTOP7SEC,       _T("停止時フェードアウト時間を7秒に設定")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_FADEOUTSTOP8SEC,       _T("停止時フェードアウト時間を8秒に設定")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_FADEOUTSTOP9SEC,       _T("停止時フェードアウト時間を9秒に設定")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_FADEOUTSTOP10SEC,       _T("停止時フェードアウト時間を10秒に設定")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_FADEOUTNEXT,           _T("曲の切替時にフェードアウト")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_FADEOUTNEXT1SEC,       _T("切替時フェードアウト時間を1秒に設定")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_FADEOUTNEXT2SEC,       _T("切替時フェードアウト時間を2秒に設定")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_FADEOUTNEXT3SEC,       _T("切替時フェードアウト時間を3秒に設定")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_FADEOUTNEXT4SEC,       _T("切替時フェードアウト時間を4秒に設定")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_FADEOUTNEXT5SEC,       _T("切替時フェードアウト時間を5秒に設定")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_FADEOUTNEXT6SEC,       _T("切替時フェードアウト時間を6秒に設定")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_FADEOUTNEXT7SEC,       _T("切替時フェードアウト時間を7秒に設定")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_FADEOUTNEXT8SEC,       _T("切替時フェードアウト時間を8秒に設定")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_FADEOUTNEXT9SEC,       _T("切替時フェードアウト時間を9秒に設定")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_FADEOUTNEXT10SEC,       _T("切替時フェードアウト時間を10秒に設定")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_TWEET,                 _T("Twitterでつぶやく")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_METRONOME,             _T("メトロノーム機能")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_QUALITY_NORMAL,        _T("音質 - ノーマル")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_QUALITY_ASIO,          _T("音質 - ASIO")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_QUALITY_WASAPI,        _T("音質 - WASAPI")},
{DIV_EFFECT,     CMD_KEYMENU,ID_ADDPRESET,             _T("現在の設定をプリセットに追加")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELETEPRESET,          _T("選択中のプリセットを削除")},
{DIV_EFFECT,     CMD_KEYMENU,ID_REVERB_DEFAULT,        _T("デフォルト（リバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_REVERB_CUSTOMIZE,      _T("カスタマイズ（リバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_DEFAULT,      _T("デフォルト（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_PADDEDCELL,   _T("クッション張りの安全室（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_ROOM,         _T("部屋（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_BATHROOM,     _T("浴室（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_LIVINGROOM,   _T("リビング（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_STONEROOM,    _T("石室（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_AUDITORIUM,   _T("講堂（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_CONCERTHALL,  _T("コンサートホール（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_CAVE,         _T("洞窟（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_ARENA,        _T("アリーナ（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_HANGAR,       _T("納屋（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_CARPETEDHALLWAY,_T("カーペットを敷いた廊下（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_HALLWAY,      _T("廊下（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_STONECORRIDOR,_T("石の廊下（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_ALLEY,        _T("裏通り（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_FOREST,       _T("森林（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_CITY,         _T("都市（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_MOUNTAINS,    _T("山（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_QUARRY,       _T("採石場（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_PLAIN,        _T("平野（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_PARKINGLOT,   _T("駐車場（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_SEWERPIPE,    _T("下水管（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_UNDERWATER,   _T("水中（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_SMALLROOM,    _T("小部屋（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_MEDIUMROOM,   _T("中部屋（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_LARGEROOM,    _T("大部屋（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_MEDIUMHALL,   _T("中ホール（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_LARGEHALL,    _T("大ホール（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_PLATE,        _T("プレート（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_CUSTOMIZE,    _T("カスタマイズ（３Ｄリバーブ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELAY_DEFAULT,         _T("デフォルト（ディレイ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELAY_SHORT,           _T("短いエコー（ディレイ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELAY_MEDIUM,          _T("中ぐらいのエコー（ディレイ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELAY_LONG,            _T("長いエコー（ディレイ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELAY_STEREOSHORT,     _T("ステレオの短いエコー（ディレイ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELAY_STEREOMEDIUM,    _T("ステレオの中ぐらいのエコー（ディレイ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELAY_STEREOLONG,      _T("ステレオの長いエコー（ディレイ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELAY_MOUNTAIN,        _T("山びこ（ディレイ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELAY_BIG,             _T("大きいエコー（ディレイ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELAY_STEREOBIG,       _T("ステレオの大きいエコー（ディレイ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELAY_DOUBLING,        _T("ダブリング（ディレイ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELAY_DOUBLEKICK,      _T("ダブルキック（ディレイ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELAY_CUSTOMIZE,       _T("カスタマイズ（ディレイ）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_CHORUS_DEFAULT,        _T("デフォルト（コーラス）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_CHORUS_CUSTOMIZE,      _T("カスタマイズ（コーラス）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_COMPRESSOR_DEFAULT,    _T("デフォルト（コンプレッサー）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_COMPRESSOR_CUSTOMIZE,  _T("カスタマイズ（コンプレッサー）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_FLANGER_DEFAULT,       _T("デフォルト（フランジャー）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_FLANGER_CUSTOMIZE,     _T("カスタマイズ（フランジャー）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_GARGLE_DEFAULT,        _T("デフォルト（ガーグル）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_GARGLE_CUSTOMIZE,      _T("カスタマイズ（ガーグル）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DISTORTION_DEFAULT,    _T("デフォルト（ディストーション）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DISTORTION_CUSTOMIZE,  _T("カスタマイズ（ディストーション）")},
{DIV_EFFECT,     CMD_KEYMENU,ID_RESETALL,              _T("全てデフォルトに戻す")},
{DIV_EFFECT,     CMD_KEYMENU,ID_RECORDNOISE,           _T("レコードノイズ")},
{DIV_EFFECT,     CMD_KEYMENU,ID_WAVE,                  _T("波音")},
{DIV_EFFECT,     CMD_KEYMENU,ID_NORMALIZE,             _T("ノーマライズ")},
{DIV_EFFECT,     CMD_KEYMENU,ID_VOCALCANCEL,           _T("ボーカルキャンセル")},
{DIV_EFFECT,     CMD_KEYMENU,ID_REVERSE,               _T("逆回転再生")},
{DIV_EFFECT,     CMD_KEYMENU,ID_RECORD,                _T("古びたレコード再生")},
{DIV_EFFECT,     CMD_KEYMENU,ID_LOWBATTERY,            _T("電池切れ")},
{DIV_EFFECT,     CMD_KEYMENU,ID_NOSENSE,               _T("歌へたモード")},
{DIV_EFFECT,     CMD_KEYMENU,ID_BASSCOPY,              _T("ベースの耳コピ")},
{DIV_EFFECT,     CMD_KEYMENU,ID_CYMBALCOPY,            _T("ドラム（ハイハット、シンバル）の耳コピ")},
{DIV_EFFECT,     CMD_KEYMENU,ID_EARTRAINING,           _T("聴覚トレーニング")},
{DIV_EFFECT,     CMD_KEYMENU,ID_MONORAL,               _T("モノラル")},
{DIV_EFFECT,     CMD_KEYMENU,ID_ONLYLEFT,              _T("左のみ再生")},
{DIV_EFFECT,     CMD_KEYMENU,ID_ONLYRIGHT,             _T("右のみ再生")},
{DIV_EFFECT,     CMD_KEYMENU,ID_CHANGELR,              _T("左右入れ替え")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQFLAT,                _T("FLAT")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQLOWSUPER,            _T("低音強調（超最強）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQLOWHIGHEST,          _T("低音強調（最強）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQLOWHIGH,             _T("低音強調（強）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQLOWMIDDLE,           _T("低音強調（中）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQLOWLOW,              _T("低音強調（弱）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQLOWLOWEST,           _T("低音強調（最弱）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQMIDDLESUPER,         _T("中音強調（超最強）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQMIDDLEHIGHEST,       _T("中音強調（最強）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQMIDDLEHIGH,          _T("中音強調（強）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQMIDDLEMIDDLE,        _T("中音強調（中）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQMIDDLELOW,           _T("中音強調（弱）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQMIDDLELOWEST,        _T("中音強調（最弱）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQHIGHSUPER,           _T("高音強調（超最強）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQHIGHHIGHEST,         _T("高音強調（最強）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQHIGHHIGH,            _T("高音強調（強）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQHIGHMIDDLE,          _T("高音強調（中）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQHIGHLOW,             _T("高音強調（弱）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQHIGHLOWEST,          _T("高音強調（最弱）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQLOWCUTSUPER,         _T("低音カット（超最強）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQLOWCUTHIGHEST,       _T("低音カット（最強）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQLOWCUTHIGH,          _T("低音カット（強）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQLOWCUTMIDDLE,        _T("低音カット（中）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQLOWCUTLOW,           _T("低音カット（弱）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQLOWCUTLOWEST,        _T("低音カット（最弱）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQMIDDLECUTSUPER,      _T("中音カット（超最強）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQMIDDLECUTHIGHEST,    _T("中音カット（最強）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQMIDDLECUTHIGH,       _T("中音カット（強）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQMIDDLECUTMIDDLE,     _T("中音カット（中）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQMIDDLECUTLOW,        _T("中音カット（弱）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQMIDDLECUTLOWEST,     _T("中音カット（最弱）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQHIGHCUTSUPER,        _T("高音カット（超最強）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQHIGHCUTHIGHEST,      _T("高音カット（最強）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQHIGHCUTHIGH,         _T("高音カット（強）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQHIGHCUTMIDDLE,       _T("高音カット（中）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQHIGHCUTLOW,          _T("高音カット（弱）")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQHIGHCUTLOWEST,       _T("高音カット（最弱）")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_DOUBLERUN,             _T("多重起動")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_TOPMOST,               _T("最前面表示")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_TASKTRAY,              _T("最小化時タスクトレイに格納")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_COPYTIME,              _T("現在の再生位置をクリップボードにコピー")},
{DIV_HELP,       CMD_KEYMENU,ID_MANUAL,                _T("マニュアル")},
{DIV_HELP,       CMD_KEYMENU,ID_UPDATECHECK,           _T("アップデートの確認")},
{DIV_HELP,       CMD_KEYMENU,ID_VERSIONINFO,           _T("バージョン情報")},
{DIV_NONE,       CMD_KEYMENU,ID_RESTORE,               _T("元のサイズに戻す")},
#else // JP
{DIV_FILE,       CMD_ALL,    ID_OPENFILE,              _T("Open file")},
{DIV_FILE,       CMD_KEYMENU,ID_ADDFILE,               _T("Add file")},
{DIV_FILE,       CMD_KEYMENU,ID_OPENFOLDER,            _T("Open directory")},
{DIV_FILE,       CMD_KEYMENU,ID_ADDFOLDER,             _T("Add directory")},
{DIV_FILE,       CMD_KEYMENU,ID_OPENURL,               _T("Open URL")},
{DIV_FILE,       CMD_KEYMENU,ID_ADDURL,                _T("Add URL")},
{DIV_FILE,       CMD_KEYMENU,ID_SAVEFILE,              _T("Save file")},
{DIV_FILE,       CMD_KEYMENU,ID_SAVEALLFILE,           _T("Save all files")},
{DIV_FILE,       CMD_KEYMENU,ID_EXIT,                  _T("Exit")},
{DIV_EDIT,       CMD_KEYMENU,ID_DELETE,                _T("Delete")},
{DIV_EDIT,       CMD_KEYMENU,ID_SELECTALL,             _T("Select all")},
{DIV_VIEW,       CMD_KEYMENU,ID_VIDEOSCREEN,           _T("Switch visibility of video screen")},
{DIV_VIEW,       CMD_KEYMENU,ID_LYRICS,                _T("Switch Visibility of Lyrics")},
{DIV_VIEW,       CMD_KEYMENU,ID_PITCHANALYSER,         _T("Switch Visibility of Pitch Analyser")},
{DIV_VIEW,       CMD_KEYMENU,ID_TIMESLIDER,            _T("Switch visibility of position slider")},
{DIV_VIEW,       CMD_KEYMENU,ID_EXPLORER,              _T("Switch visibility of explorer")},
{DIV_VIEW,       CMD_KEYMENU,ID_SPEED,                 _T("Switch visibility of speed control")},
{DIV_VIEW,       CMD_KEYMENU,ID_FREQ,                  _T("Switch visibility of frequency control")},
{DIV_VIEW,       CMD_KEYMENU,ID_PITCH,                 _T("Switch visibility of pitch control")},
{DIV_VIEW,       CMD_KEYMENU,ID_VOLUME,                _T("Switch visibility of volume control")},
{DIV_VIEW,       CMD_KEYMENU,ID_PAN,                   _T("Switch visibility of pan control")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ,                    _T("Switch visibility of EQ")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ20,                  _T("Switch visibility of EQ 20 Hz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ25,                  _T("Switch visibility of EQ 25 Hz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ31_5,                _T("Switch visibility of EQ 31.5 Hz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ40,                  _T("Switch visibility of EQ 40 Hz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ50,                  _T("Switch visibility of EQ 50 Hz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ63,                  _T("Switch visibility of EQ 63 Hz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ80,                  _T("Switch visibility of EQ 80 Hz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ100,                 _T("Switch visibility of EQ 100 Hz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ125,                 _T("Switch visibility of EQ 125 Hz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ160,                 _T("Switch visibility of EQ 160 Hz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ200,                 _T("Switch visibility of EQ 200 Hz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ250,                 _T("Switch visibility of EQ 250 Hz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ315,                 _T("Switch visibility of EQ 315 Hz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ400,                 _T("Switch visibility of EQ 400 Hz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ500,                 _T("Switch visibility of EQ 500 Hz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ630,                 _T("Switch visibility of EQ 630 Hz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ800,                 _T("Switch visibility of EQ 800 Hz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ1K,                  _T("Switch visibility of EQ 1 KHz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ1_25K,               _T("Switch visibility of EQ 1.25 KHz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ1_6K,                _T("Switch visibility of EQ 1.6 KHz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ2K,                  _T("Switch visibility of EQ 2 KHz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ2_5K,                _T("Switch visibility of EQ 2.5 KHz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ3_15K,               _T("Switch visibility of EQ 3.15 KHz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ4K,                  _T("Switch visibility of EQ 4 KHz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ5K,                  _T("Switch visibility of EQ 5 KHz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ6_3K,                _T("Switch visibility of EQ 6.3 KHz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ8K,                  _T("Switch visibility of EQ 8 KHz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ10K,                 _T("Switch visibility of EQ 10 KHz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ12_5K,               _T("Switch visibility of EQ 12.5 KHz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ16K,                 _T("Switch visibility of EQ 16 KHz")},
{DIV_VIEW,       CMD_KEYMENU,ID_EQ20K,                 _T("Switch visibility of EQ 20 KHz")},
{DIV_VIEW,       CMD_ALL,    ID_TAB,                   _T("Switch visibility of tab")},
{DIV_VIEW,       CMD_ALL,    ID_PLAYLIST,              _T("Switch visibility of playlist")},
{DIV_VIEW,       CMD_ALL,    ID_CLOSEALL,              _T("Close all")},
{DIV_VIEW,       CMD_KEYMENU,ID_TOOLBAR_SIZES,         _T("Toolbar S size")},
{DIV_VIEW,       CMD_KEYMENU,ID_TOOLBAR_SIZEM,         _T("Toolbar M size")},
{DIV_VIEW,       CMD_KEYMENU,ID_TOOLBAR_SIZEL,         _T("Toolbar L size")},
{DIV_VIEW,       CMD_KEYMENU,ID_CUSTOMIZETOOLBAR,      _T("Customize toolbar")},
{DIV_PLAY,       CMD_TOOLBAR,ID_PLAY,                  _T("Play")},
{DIV_PLAY,       CMD_ALL,    ID_PAUSE,                 _T("Play/Pause")},
{DIV_PLAY,       CMD_ALL,    ID_STOP,                  _T("Stop")},
{DIV_PLAY,       CMD_ALL,    ID_HEAD,                  _T("Head")},
{DIV_PLAY,       CMD_NONE,   ID_PREVMARKER,            _T("Previous marker")},
{DIV_PLAY,       CMD_KEYMENU,ID_PREV,                  _T("Previous")},
{DIV_PLAY,       CMD_NONE,   ID_NEXTMARKER,            _T("Next marker")},
{DIV_PLAY,       CMD_ALL,    ID_NEXT,                  _T("Next")},
{DIV_PLAY,       CMD_KEYMENU,ID_REWIND,                _T("Rewind")},
{DIV_PLAY,       CMD_KEYMENU,ID_FORWARD,               _T("Forward")},
{DIV_BACKWARD,   CMD_KEYSET, ID_PAUSE_RETURN1SEC,      _T("Pause and Rewind 1 sec.")},
{DIV_BACKWARD,   CMD_KEYSET, ID_PAUSE_RETURN2SEC,      _T("Pause and Rewind 2 sec.")},
{DIV_BACKWARD,   CMD_KEYSET, ID_PAUSE_RETURN3SEC,      _T("Pause and Rewind 3 sec.")},
{DIV_BACKWARD,   CMD_KEYSET, ID_PAUSE_RETURN5SEC,      _T("Pause and Rewind 5 sec.")},
{DIV_BACKWARD,   CMD_KEYSET, ID_PAUSE_RETURN10SEC,     _T("Pause and Rewind 10 sec.")},
{DIV_BACKWARD,   CMD_KEYMENU,ID_RETURN1SEC,            _T("Rewind 1 sec.")},
{DIV_BACKWARD,   CMD_KEYMENU,ID_RETURN2SEC,            _T("Rewind 2 sec.")},
{DIV_BACKWARD,   CMD_KEYMENU,ID_RETURN3SEC,            _T("Rewind 3 sec.")},
{DIV_BACKWARD,   CMD_KEYMENU,ID_RETURN5SEC,            _T("Rewind 5 sec.")},
{DIV_BACKWARD,   CMD_KEYMENU,ID_RETURN10SEC,           _T("Rewind 10 sec.")},
{DIV_FORWARD,    CMD_KEYMENU,ID_FORWARD1SEC,           _T("Forward 1 sec.")},
{DIV_FORWARD,    CMD_KEYMENU,ID_FORWARD2SEC,           _T("Forward 2 sec.")},
{DIV_FORWARD,    CMD_KEYMENU,ID_FORWARD3SEC,           _T("Forward 3 sec.")},
{DIV_FORWARD,    CMD_KEYMENU,ID_FORWARD5SEC,           _T("Forward 5 sec.")},
{DIV_FORWARD,    CMD_KEYMENU,ID_FORWARD10SEC,          _T("Forward 10 sec.")},
{DIV_SPEED,      CMD_KEYMENU,ID_RESETSPEED,            _T("Reset speed")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_50,              _T("Set Speed 50%")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_60,              _T("Set Speed 60%")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_70,              _T("Set Speed 70%")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_80,              _T("Set Speed 80%")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_90,              _T("Set Speed 90%")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_100,             _T("Set Speed 100%")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_110,             _T("Set Speed 110%")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_120,             _T("Set Speed 120%")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_130,             _T("Set Speed 130%")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_140,             _T("Set Speed 140%")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_150,             _T("Set Speed 150%")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_160,             _T("Set Speed 160%")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_170,             _T("Set Speed 170%")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_180,             _T("Set Speed 180%")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_190,             _T("Set Speed 190%")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_200,             _T("Set Speed 200%")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_250,             _T("Set Speed 250%")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_300,             _T("Set Speed 300%")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_350,             _T("Set Speed 350%")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEED_400,             _T("Set Speed 400%")},
{DIV_SPEED,      CMD_KEYMENU,ID_DOWN0_1SPEED,          _T("Turn down speed 0.1%")},
{DIV_SPEED,      CMD_KEYMENU,ID_DOWN1SPEED,            _T("Turn down speed 1%")},
{DIV_SPEED,      CMD_KEYMENU,ID_DOWN2SPEED,            _T("Turn down speed 2%")},
{DIV_SPEED,      CMD_KEYMENU,ID_DOWN3SPEED,            _T("Turn down speed 3%")},
{DIV_SPEED,      CMD_KEYMENU,ID_DOWN5SPEED,            _T("Turn down speed 5%")},
{DIV_SPEED,      CMD_KEYMENU,ID_DOWN10SPEED,           _T("Turn down speed 10%")},
{DIV_SPEED,      CMD_KEYMENU,ID_UP0_1SPEED,            _T("Turn up speed 0.1%")},
{DIV_SPEED,      CMD_KEYMENU,ID_UP1SPEED,              _T("Turn up speed 1%")},
{DIV_SPEED,      CMD_KEYMENU,ID_UP2SPEED,              _T("Turn up speed 2%")},
{DIV_SPEED,      CMD_KEYMENU,ID_UP3SPEED,              _T("Turn up speed 3%")},
{DIV_SPEED,      CMD_KEYMENU,ID_UP5SPEED,              _T("Turn up speed 5%")},
{DIV_SPEED,      CMD_KEYMENU,ID_UP10SPEED,             _T("Turn up speed 10%")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEEDDEC_0,            _T("Set speed decimal digit 0.")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEEDDEC_1,            _T("Set speed decimal digit 1.")},
{DIV_SPEED,      CMD_KEYMENU,ID_SPEEDDEC_2,            _T("Set speed decimal digit 2.")},
{DIV_FREQ,       CMD_KEYMENU,ID_RESETFREQ,             _T("Reset frequency")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_50,                _T("Set Frequency 50%")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_60,                _T("Set Frequency 60%")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_70,                _T("Set Frequency 70%")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_80,                _T("Set Frequency 80%")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_90,                _T("Set Frequency 90%")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_100,               _T("Set Frequency 100%")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_110,               _T("Set Frequency 110%")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_120,               _T("Set Frequency 120%")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_130,               _T("Set Frequency 130%")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_140,               _T("Set Frequency 140%")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_150,               _T("Set Frequency 150%")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_160,               _T("Set Frequency 160%")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_170,               _T("Set Frequency 170%")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_180,               _T("Set Frequency 180%")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_190,               _T("Set Frequency 190%")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_200,               _T("Set Frequency 200%")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_250,               _T("Set Frequency 250%")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_300,               _T("Set Frequency 300%")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_350,               _T("Set Frequency 350%")},
{DIV_FREQ,      CMD_KEYMENU,ID_FREQ_400,               _T("Set Frequency 400%")},
{DIV_FREQ,       CMD_KEYMENU,ID_DOWN0_1FREQ,           _T("Turn up frequency 0.1%")},
{DIV_FREQ,       CMD_KEYMENU,ID_DOWN1FREQ,             _T("Turn down frequency 1%")},
{DIV_FREQ,       CMD_KEYMENU,ID_DOWN2FREQ,             _T("Turn down frequency 2%")},
{DIV_FREQ,       CMD_KEYMENU,ID_DOWN3FREQ,             _T("Turn down frequency 3%")},
{DIV_FREQ,       CMD_KEYMENU,ID_DOWN5FREQ,             _T("Turn down frequency 5%")},
{DIV_FREQ,       CMD_KEYMENU,ID_DOWN10FREQ,            _T("Turn down frequency 10%")},
{DIV_FREQ,       CMD_KEYMENU,ID_UP0_1FREQ,             _T("Turn up frequency 0.1%")},
{DIV_FREQ,       CMD_KEYMENU,ID_UP1FREQ,               _T("Turn up frequency 1%")},
{DIV_FREQ,       CMD_KEYMENU,ID_UP2FREQ,               _T("Turn up frequency 2%")},
{DIV_FREQ,       CMD_KEYMENU,ID_UP3FREQ,               _T("Turn up frequency 3%")},
{DIV_FREQ,       CMD_KEYMENU,ID_UP5FREQ,               _T("Turn up frequency 5%")},
{DIV_FREQ,       CMD_KEYMENU,ID_UP10FREQ,              _T("Turn up frequency 10%")},
{DIV_FREQ,       CMD_KEYMENU,ID_FREQDEC_0,             _T("Set frequency decimal digit 0.")},
{DIV_FREQ,       CMD_KEYMENU,ID_FREQDEC_1,             _T("Set frequency decimal digit 1.")},
{DIV_FREQ,       CMD_KEYMENU,ID_FREQDEC_2,             _T("Set frequency decimal digit 2.")},
{DIV_PITCH,      CMD_KEYMENU,ID_RESETPITCH,            _T("Reset pitch")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_F12,             _T("Set Pitch ♭12")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_F11,             _T("Set Pitch ♭11")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_F10,             _T("Set Pitch ♭10")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_F9,              _T("Set Pitch ♭9")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_F8,              _T("Set Pitch ♭8")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_F7,              _T("Set Pitch ♭7")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_F6,              _T("Set Pitch ♭6")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_F5,              _T("Set Pitch ♭5")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_F4,              _T("Set Pitch ♭4")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_F3,              _T("Set Pitch ♭3")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_F2,              _T("Set Pitch ♭2")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_F1,              _T("Set Pitch ♭1")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_0,               _T("Set Pitch Natural")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_S1,              _T("Set Pitch ♯1")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_S2,              _T("Set Pitch ♯2")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_S3,              _T("Set Pitch ♯3")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_S4,              _T("Set Pitch ♯4")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_S5,              _T("Set Pitch ♯5")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_S6,              _T("Set Pitch ♯6")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_S7,              _T("Set Pitch ♯7")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_S8,              _T("Set Pitch ♯8")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_S9,              _T("Set Pitch ♯9")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_S10,             _T("Set Pitch ♯10")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_S11,             _T("Set Pitch ♯11")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCH_S12,             _T("Set Pitch ♯12")},
{DIV_PITCH,      CMD_KEYMENU,ID_DOWN1PITCH,            _T("Flat")},
{DIV_PITCH,      CMD_KEYMENU,ID_DOWN2PITCH,            _T("Double flat")},
{DIV_PITCH,      CMD_KEYMENU,ID_DOWN1OCTPITCH,         _T("Down 1 Octave")},
{DIV_PITCH,      CMD_KEYMENU,ID_UP1PITCH,              _T("Sharp")},
{DIV_PITCH,      CMD_KEYMENU,ID_UP2PITCH,              _T("Double sharp")},
{DIV_PITCH,      CMD_KEYMENU,ID_UP1OCTPITCH,           _T("Up 1 Octave")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCHDEC_0,            _T("Set pitch decimal digit 0.")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCHDEC_1,            _T("Set pitch decimal digit 1.")},
{DIV_PITCH,      CMD_KEYMENU,ID_PITCHDEC_2,            _T("Set pitch decimal digit 2.")},
{DIV_PLAY,       CMD_KEYMENU,ID_RESETVOLUME,           _T("Reset Volume")},
{DIV_PLAY,       CMD_KEYMENU,ID_VOLUME_0,              _T("Set Volume 0%")},
{DIV_PLAY,       CMD_KEYMENU,ID_VOLUME_10,             _T("Set Volume 10%")},
{DIV_PLAY,       CMD_KEYMENU,ID_VOLUME_20,             _T("Set Volume 20%")},
{DIV_PLAY,       CMD_KEYMENU,ID_VOLUME_30,             _T("Set Volume 30%")},
{DIV_PLAY,       CMD_KEYMENU,ID_VOLUME_40,             _T("Set Volume 40%")},
{DIV_PLAY,       CMD_KEYMENU,ID_VOLUME_50,             _T("Set Volume 50%")},
{DIV_PLAY,       CMD_KEYMENU,ID_VOLUME_60,             _T("Set Volume 60%")},
{DIV_PLAY,       CMD_KEYMENU,ID_VOLUME_70,             _T("Set Volume 70%")},
{DIV_PLAY,       CMD_KEYMENU,ID_VOLUME_80,             _T("Set Volume 80%")},
{DIV_PLAY,       CMD_KEYMENU,ID_VOLUME_90,             _T("Set Volume 90%")},
{DIV_PLAY,       CMD_KEYMENU,ID_VOLUME_100,            _T("Set Volume 100%")},
{DIV_PLAY,       CMD_KEYSET, ID_UPVOLUME,              _T("Turn up volume 1%")},
{DIV_PLAY,       CMD_KEYSET, ID_DOWNVOLUME,            _T("Turn down volume 1%")},
{DIV_PLAY,       CMD_ALL,    ID_SLOOP,                 _T("Single loop")},
{DIV_PLAY,       CMD_ALL,    ID_ALOOP,                 _T("All loop")},
{DIV_PLAY,       CMD_ALL,    ID_RANDOM,                _T("Random play")},
{DIV_PLAY,       CMD_KEYMENU,ID_CONTINUE,              _T("Continuous play")},
{DIV_PLAY,       CMD_ALL,    ID_SAMEARTIST,            _T("Same Artist")},
{DIV_PLAY,       CMD_ALL,    ID_ABLOOP_A,              _T("AB loop(A)")},
{DIV_PLAY,       CMD_ALL,    ID_ABLOOP_A_SETTING,      _T("AB loop(A) pos setting")},
{DIV_PLAY,       CMD_ALL,    ID_ABLOOP_B,              _T("AB loop(B)")},
{DIV_PLAY,       CMD_ALL,    ID_ABLOOP_B_SETTING,      _T("AB loop(B) pos setting")},
{DIV_PLAY,       CMD_ALL,    ID_MARKERPLAY,            _T("Marker play")},
{DIV_PLAY,       CMD_ALL,    ID_ADDMARKER,             _T("Add a marker")},
{DIV_PLAY,       CMD_ALL,    ID_DELETEMARKER,          _T("Delete a marker")},
{DIV_PLAY,       CMD_KEYMENU,ID_COUNTLOOP,             _T("Count loop")},
{DIV_PLAY,       CMD_KEYMENU,ID_INSTANTLOOP,           _T("Loop when adding a marker")},
{DIV_PLAY,       CMD_KEYMENU,ID_SETPOSITIONAUTO,       _T("Set position automatic when adjusting marker position")},
{DIV_RCV_VISIBLE,CMD_KEYMENU,ID_RECOVERVIDEOSCREENVISIBLE,_T("Recover visibility of video screen")},
{DIV_RCV_VISIBLE,CMD_KEYMENU,ID_RECOVERTIMESLIDERVISIBLE,_T("Recover visibility of position slider")},
{DIV_RCV_VISIBLE,CMD_KEYMENU,ID_RECOVERSPEEDVISIBLE,   _T("Recover visibility of speed control")},
{DIV_RCV_VISIBLE,CMD_KEYMENU,ID_RECOVERFREQVISIBLE,    _T("Recover visibility of frequency control")},
{DIV_RCV_VISIBLE,CMD_KEYMENU,ID_RECOVERPITCHVISIBLE,   _T("Recover visibility of pitch control")},
{DIV_RCV_VISIBLE,CMD_KEYMENU,ID_RECOVERVOLUMEVISIBLE,  _T("Recover visibility of volume control")},
{DIV_RCV_VISIBLE,CMD_KEYMENU,ID_RECOVERPANVISIBLE,     _T("Recover visibility of pan control")},
{DIV_RCV_VISIBLE,CMD_KEYMENU,ID_RECOVEREQVISIBLE,      _T("Recover visibility of graphic equalizer")},
{DIV_RCV_VISIBLE,CMD_KEYMENU,ID_RECOVERLISTVISIBLE,    _T("Recover visibility of playlist")},
{DIV_RCV_MODE,   CMD_KEYMENU,ID_RECOVERSLOOP,          _T("Recover single loop")},
{DIV_RCV_MODE,   CMD_KEYMENU,ID_RECOVERALOOP,          _T("Recover all loop")},
{DIV_RCV_MODE,   CMD_KEYMENU,ID_RECOVERRANDOM,         _T("Recover random play")},
{DIV_RCV_MODE,   CMD_KEYMENU,ID_RECOVERCONTINUE,       _T("Recover continuous play")},
{DIV_RCV_MODE,   CMD_KEYMENU,ID_RECOVERINSTANTLOOP,    _T("Recover looping when adding a marker")},
{DIV_RCV_MODE,   CMD_KEYMENU,ID_RECOVERSETPOSITIONAUTO,_T("Recover setting position automatic when adjusting marker position")},
{DIV_RCV_MODE,   CMD_KEYMENU,ID_RECOVERREVERSE,        _T("Recover reverse play")},
{DIV_RCV_MODE,   CMD_KEYMENU,ID_RECOVERRECORD,         _T("Recover old record play")},
{DIV_RECOVERY,   CMD_KEYMENU,ID_RECOVERWPOS,           _T("Recover window position")},
{DIV_RECOVERY,   CMD_KEYMENU,ID_RECOVERWSIZE,          _T("Recover window size")},
{DIV_RECOVERY,   CMD_KEYMENU,ID_RECOVERPLAYPOS,        _T("Recover Play Position")},
{DIV_RECOVERY,   CMD_KEYMENU,ID_RECOVERSPEED,          _T("Recover speed")},
{DIV_RECOVERY,   CMD_KEYMENU,ID_RECOVERFREQ,           _T("Recover frequency")},
{DIV_RECOVERY,   CMD_KEYMENU,ID_RECOVERPITCH,          _T("Recover pitch")},
{DIV_RECOVERY,   CMD_KEYMENU,ID_RECOVERVOLUME,         _T("Recover volume")},
{DIV_RECOVERY,   CMD_KEYMENU,ID_RECOVERPAN,            _T("Recover pan")},
{DIV_RECOVERY,   CMD_KEYMENU,ID_RECOVEREQ,             _T("Recover graphic equalizer")},
{DIV_RECOVERY,   CMD_KEYMENU,ID_RECOVERLIST,           _T("Recover playlist")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_KEYSETTING,            _T("Shortcut key setting")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_OUTKEYSETTING,         _T("Global hot key setting")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_LIMIT,                 _T("Max/Min setting")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_TIMERPLAY,             _T("Timer setting")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_PLAYRANGE,             _T("Play Range")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_PLAYPOSITION,          _T("Play position")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_INCSPEED,              _T("Increase speed")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_INCFREQ,               _T("Increase frequency")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_DECSPEED,              _T("Decrease speed")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_DECFREQ,               _T("Decrease frequency")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_FADEOUTSTOP,           _T("Fade out stop")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_FADEOUTNEXT,           _T("Fade out next")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_FADEOUTNEXT3SEC,       _T("Fade out next(3sec)")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_FADEOUTNEXT5SEC,       _T("Fade out next(5sec)")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_TWEET,                 _T("Tweet on Twitter")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_METRONOME,             _T("Metronome")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_QUALITY_NORMAL,        _T("Quality - Normal")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_QUALITY_ASIO,          _T("Quality - ASIO")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_QUALITY_WASAPI,        _T("Quality - WASAPI")},
{DIV_EFFECT,     CMD_KEYMENU,ID_ADDPRESET,             _T("Add current settings to preset")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELETEPRESET,          _T("Delete selected preset")},
{DIV_EFFECT,     CMD_KEYMENU,ID_REVERB_DEFAULT,        _T("Default(Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_REVERB_CUSTOMIZE,      _T("Customize(Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_DEFAULT,      _T("Default(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_PADDEDCELL,   _T("Padded Cell(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_ROOM,         _T("Room(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_BATHROOM,     _T("Bathroom(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_LIVINGROOM,   _T("Living Room(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_STONEROOM,    _T("Stone Room(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_AUDITORIUM,   _T("Auditorium(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_CONCERTHALL,  _T("Concert Hall(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_CAVE,         _T("Cave(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_ARENA,        _T("Arena(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_HANGAR,       _T("Hangar(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_CARPETEDHALLWAY,_T("Carpeted Hallway(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_HALLWAY,      _T("Hallway(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_STONECORRIDOR,_T("Stone Corridor(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_ALLEY,        _T("Alley(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_FOREST,       _T("Forest(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_CITY,         _T("City(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_MOUNTAINS,    _T("Mountains(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_QUARRY,       _T("Quarry(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_PLAIN,        _T("Plain(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_PARKINGLOT,   _T("Parking Lot(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_SEWERPIPE,    _T("Sewer Pipe(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_UNDERWATER,   _T("Underwater(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_SMALLROOM,    _T("Small Room(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_MEDIUMROOM,   _T("Medium Room(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_LARGEROOM,    _T("Large Room(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_MEDIUMHALL,   _T("Medium Hall(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_LARGEHALL,    _T("Large Hall(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_PLATE,        _T("Plate(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_3DREVERB_CUSTOMIZE,    _T("Customize(3D Reverb)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELAY_DEFAULT,         _T("Default(Delay)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELAY_SHORT,           _T("Short Echo(Delay)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELAY_MEDIUM,          _T("Medium Echo(Delay)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELAY_LONG,            _T("Long Echo(Delay)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELAY_STEREOSHORT,     _T("Stereo Short Echo(Delay)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELAY_STEREOMEDIUM,    _T("Stereo Medium Echo(Delay)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELAY_STEREOLONG,      _T("Stereo Long Echo(Delay)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELAY_MOUNTAIN,        _T("Mountain Echo(Delay)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELAY_BIG,             _T("Big Echo(Delay)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELAY_STEREOBIG,       _T("Stereo Big Echo(Delay)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELAY_DOUBLING,        _T("Doubling(Delay)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELAY_DOUBLEKICK,      _T("Double Kick(Delay)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DELAY_CUSTOMIZE,       _T("Customize(Delay")},
{DIV_EFFECT,     CMD_KEYMENU,ID_CHORUS_DEFAULT,        _T("Default(Chorus)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_CHORUS_CUSTOMIZE,      _T("Customize(Chorus)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_COMPRESSOR_DEFAULT,    _T("Default(Compressor)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_COMPRESSOR_CUSTOMIZE,  _T("Customize(Compressor)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_FLANGER_DEFAULT,       _T("Default(Flanger)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_FLANGER_CUSTOMIZE,     _T("Customize(Flanger)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_GARGLE_DEFAULT,        _T("Default(Gargle)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_GARGLE_CUSTOMIZE,      _T("Customize(Gargle)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DISTORTION_DEFAULT,    _T("Default(Distortion)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_DISTORTION_CUSTOMIZE,  _T("Customize(Distortion)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_RESETALL,              _T("Reset all")},
{DIV_EFFECT,     CMD_KEYMENU,ID_RECORDNOISE,           _T("Record Noise")},
{DIV_EFFECT,     CMD_KEYMENU,ID_WAVE,                  _T("Wave")},
{DIV_EFFECT,     CMD_KEYMENU,ID_NORMALIZE,             _T("Normalize")},
{DIV_EFFECT,     CMD_KEYMENU,ID_VOCALCANCEL,           _T("Vocal cancel")},
{DIV_EFFECT,     CMD_KEYMENU,ID_REVERSE,               _T("Reverse play")},
{DIV_EFFECT,     CMD_KEYMENU,ID_RECORD,                _T("Old record play")},
{DIV_EFFECT,     CMD_KEYMENU,ID_LOWBATTERY,            _T("Low battery")},
{DIV_EFFECT,     CMD_KEYMENU,ID_NOSENSE,               _T("No sense")},
{DIV_EFFECT,     CMD_KEYMENU,ID_BASSCOPY,              _T("Transcribe bass")},
{DIV_EFFECT,     CMD_KEYMENU,ID_CYMBALCOPY,            _T("Transcribe Drums (Hi-Hat, Cymbals)")},
{DIV_EFFECT,     CMD_KEYMENU,ID_EARTRAINING,           _T("Ear Training")},
{DIV_EFFECT,     CMD_KEYMENU,ID_MONORAL,               _T("Monoral")},
{DIV_EFFECT,     CMD_KEYMENU,ID_ONLYLEFT,              _T("Only left")},
{DIV_EFFECT,     CMD_KEYMENU,ID_ONLYRIGHT,             _T("Only right")},
{DIV_EFFECT,     CMD_KEYMENU,ID_CHANGELR,              _T("Change LR")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQFLAT,                _T("Set EQ flat")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQLOWSUPER,            _T("Set EQ Boost low(ultra-strong)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQLOWHIGHEST,          _T("Set EQ Boost low(strongest)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQLOWHIGH,             _T("Set EQ Boost low(strong)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQLOWMIDDLE,           _T("Set EQ Boost low(middle)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQLOWLOW,              _T("Set EQ Boost low(weak)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQLOWLOWEST,           _T("Set EQ Boost low(weakest)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQMIDDLESUPER,         _T("Set EQ Boost middle(ultra-strong)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQMIDDLEHIGHEST,       _T("Set EQ Boost middle(strongest)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQMIDDLEHIGH,          _T("Set EQ Boost middle(strong)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQMIDDLEMIDDLE,        _T("Set EQ Boost middle(middle)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQMIDDLELOW,           _T("Set EQ Boost middle(weak)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQMIDDLELOWEST,        _T("Set EQ Boost middle(weakest)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQHIGHSUPER,           _T("Set EQ Boost high(ultra-strong)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQHIGHHIGHEST,         _T("Set EQ Boost high(strongest)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQHIGHHIGH,            _T("Set EQ Boost high(strong)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQHIGHMIDDLE,          _T("Set EQ Boost high(middle)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQHIGHLOW,             _T("Set EQ Boost high(weak)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQHIGHLOWEST,          _T("Set EQ Boost high(weakest)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQLOWCUTSUPER,         _T("Set EQ low cut(ultra-strong)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQLOWCUTHIGHEST,       _T("Set EQ low cut(strongest)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQLOWCUTHIGH,          _T("Set EQ low cut(strong)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQLOWCUTMIDDLE,        _T("Set EQ low cut(middle)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQLOWCUTLOW,           _T("Set EQ low cut(weak)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQLOWCUTLOWEST,        _T("Set EQ low cut(weakest)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQMIDDLECUTSUPER,      _T("Set EQ middle cut(ultra-strong)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQMIDDLECUTHIGHEST,    _T("Set EQ middle cut(strongest)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQMIDDLECUTHIGH,       _T("Set EQ middle cut(strong)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQMIDDLECUTMIDDLE,     _T("Set EQ middle cut(middle)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQMIDDLECUTLOW,        _T("Set EQ middle cut(weak)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQMIDDLECUTLOWEST,     _T("Set EQ middle cut(weakest)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQHIGHCUTSUPER,        _T("Set EQ high cut(ultra-strong)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQHIGHCUTHIGHEST,      _T("Set EQ high cut(strongest)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQHIGHCUTHIGH,         _T("Set EQ high cut(strong)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQHIGHCUTMIDDLE,       _T("Set EQ high cut(middle)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQHIGHCUTLOW,          _T("Set EQ high cut(weak)")},
{DIV_EQ_PRESET,  CMD_KEYMENU,ID_EQHIGHCUTLOWEST,       _T("Set EQ high cut(weakest)")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_DOUBLERUN,             _T("Double runnable")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_TOPMOST,               _T("Bring window top")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_TASKTRAY,              _T("Minimize to system tray")},
{DIV_SYSTEM,     CMD_KEYMENU,ID_COPYTIME,              _T("Copy current position to clipboard")},
{DIV_HELP,       CMD_KEYMENU,ID_MANUAL,                _T("Manual")},
{DIV_HELP,       CMD_KEYMENU,ID_UPDATECHECK,           _T("Update Check")},
{DIV_HELP,       CMD_KEYMENU,ID_VERSIONINFO,           _T("Version")},
{DIV_NONE,       CMD_KEYMENU,ID_RESTORE,               _T("Restore")},
#endif // JP
{DIV_TERMINAL,   NULL,       NULL,                     NULL}
};

CCommandList::CCommandList()
{
	m_list = cmdlist;
}

WORD CCommandList::GetCommandId(tstring str)
{
	for (int i = 0; m_list[i].div != DIV_TERMINAL; i++)
	{
		if (str == m_list[i].pszText)
			return m_list[i].id;
	}

	return -1;
}

tstring CCommandList::GetCommandName(int id)
{
	for (int i = 0; m_list[i].div != DIV_TERMINAL; i++)
	{
		if (id == m_list[i].id)
			return m_list[i].pszText;
	}

	return _T("");
}
